version: '3'

services:
  demo-api:
   image: demo-api
   build: "./demo-api"
   env_file:
     - ".env"
   environment:
     - SERVICE_PORTS=8080
   ports:
     - "8080:8080"
   command: "lein run"
   deploy:
     replicas: 5
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  load-balancer:
    image: dockercloud/haproxy
    depends_on:
      - demo-api
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay